package helpers

val LeetAlphabet: Map<String, String> = mapOf(
    "A" to "4",
    "B" to "8",
    "C" to "(",
    "D" to "|)",
    "E" to "3",
    "F" to "7",
    "G" to "9",
    "H" to "I-I",
    "I" to "I",
    "J" to "√",
    "K" to "|<",
    "L" to "|_",
    "M" to "|\\/|",
    "N" to "|\\|",
    "O" to "0",
    "P" to "|o",
    "Q" to "O_",
    "R" to "|2",
    "S" to "5",
    "T" to "'|'",
    "U" to "|_|",
    "V" to "\\/",
    "W" to "\\/\\/",
    "X" to "}{",
    "Y" to "¥",
    "Z" to "7_"
)